# separate truncate lengths for console and file output
# it's easier to read in the console if its shorter, however
# storing the entire line in the output can balloon if we log
# base64 representations of files.
truncateLineLengthConsole = 128
truncateLineLengthFile = 1024

# set this to a filename to append logs to that file
writeToFile = false

[[processes]]
name = "browser"
exec = "./3suite-browser.app/Contents/MacOS/3suite-browser"
loadConfig = "browser"

[[processes]]
name = "httpServer"
exec = "./3suite-http-server"
tomlConfig = {port = 4004, directory = "node_modules"}


[configs.browser]
url = "http://localhost:4004/3lib-config/main.js"
fullscreen = false
disableCursor = false

windowWidth = 800
windowHeight = 600
